### ISSUE TITLE
Not able to retrieve token after upgrading from 0.7.0 to 1.0.0 or newer 

### ISSUE THREAD

**Issue by lelimit** [vippsas/deno-sdk#47] opened 2024-03-07 09:59 UTC
**Describe the bug** 

 😟 Error retrieving token 😟
 {
	 ok: false,
	 error: {
	 error: 'invalid_scope',
	 error_description: "AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope [object Object]/.default is not valid. Trace ID: cc6bae79-9dae-451a-9dde-a4dedf775100 Correlation ID: d6b89cfd-2658-47b9-a184-10e950bf083f Timestamp: 2024-03-07 09:49:08Z",
	 error_codes: [ 70011 ],
	 timestamp: '2024-03-07 09:49:08Z',
	 trace_id: 'cc6bae79-9dae-451a-9dde-a4dedf775100',
	 correlation_id: 'd6b89cfd-2658-47b9-a184-10e950bf083f'
	 }
 }

**To Reproduce** Steps to reproduce the behavior:

Use the sample code in sample_code/recurring_agreement_sample.ts

**Expected behavior** 
Work as before

**Comment by flinkgutt** [comment] 2024-03-07 14:34
Hi!
I'm unable to reproduce this error in our merchant test (MT) environment using v1.2.0, I'm suspecting that this particular error comes directly from Azure and might be a temporary thing.

I ran the sample with v1.2.0 as defined in the import ```import { Client } from "https://deno.land/x/vipps_mobilepay_sdk@1.2.0/mod.ts";```
Command:```deno run -A sample/recurring_agreement_sample.ts```

Could you try to run this with that particular version?
And if it still doesn't work, let us know which MerchantSerialNumber this applies to and in which environment you are testing this in.
And if it should work 🤞, please let us know as well 😀

**Comment by flinkgutt** [comment] 2024-03-19 14:22
With no reply in two weeks I'll close this issue.

**Closed by flinkgutt** 2024-03-19 14:22 UTC
