### ISSUE TITLE
Pricing type is incorrect

### ISSUE THREAD

**Issue by spiftire** [vippsas/deno-sdk#73] opened 2024-10-30 15:32 UTC
**Describe the bug** A clear and concise description of what the bug is.
The type of the pricing object provided by the SDK is not the same as what is returned by the API. It seems that the API documentation is also out of sync. https://developer.vippsmobilepay.com/api/recurring/#tag/Agreement-v3-endpoints/operation/FetchAgreementV3

**To Reproduce** Steps to reproduce the behavior:

1. Use SDK to make call like so
```ts
const agreement = await vippsClient.recurring.agreement.info(
     token,
     agreementId
    );
```
2. The response of `agreement.data.pricing` is 
```json
      "pricing": {
        "currency": "NOK",
        "amount": 5900,
        "type": "LEGACY"
      },
```
Typescript type is
```ts
export type LegacyPricingResponse = {
    /**
     * The type of pricing. This decides which properties are present.
     */
    type: "LegacyPricingResponse";
    currency: CurrencyV3;
    /**
     * The price of the agreement, present if type is LEGACY.
     *
     * Amounts are specified in minor units.
     * NOK and DKK: 1 kr = 100 øre. EUR: 1 Euro = 100 cent.
     */
    amount: number;
};
```

**Expected behavior** A clear and concise description of what you expected to
happen.
Expected SDK to have same type as returned from the API

**Screenshots** If applicable, add screenshots to help explain your problem.
Type in IDE:
![Image](https://github.com/user-attachments/assets/2b9a9532-2918-41d2-b095-287422c43db4)

From the api documentation
![Image](https://github.com/user-attachments/assets/ef7f6c44-8236-464a-b600-ea466cdbb7f9)

**Additional context** Add any other context about the problem here.
    "@vippsmobilepay/sdk": "^2.4.1",

**Comment by tomas-zijdemans-vipps** [comment] 2024-11-04 09:45
Thank you for reporting! I'll get a fix out shortly for this.

**Comment by tomas-zijdemans-vipps** [comment] 2024-11-04 10:14
So the issue here is that when using agreement.info, the SDK does not know if a Legacy or Variable pricing response is returned. So the inferred type you get (with only type and currency) is the common keys between LegacyPricingResponse and VariableAmountPricing.

Possible solution:
You could add a simple type guard like so:
![Image](https://github.com/user-attachments/assets/183302d9-022f-4eea-a27f-a9c2eb197abe)

The pricing type is set when you create the agreement, so there might be other ways of solving it more elegantly on your end.

Let me know if you see a better solution here, more than happy to discuss other options :)

**Comment by spiftire** [comment] 2024-11-04 22:23
I dont think the type guard you suggest would work in production as the value of `pricing.type` returned from the api is not `LegacyPricingResponse`, but in fact is just `LEGACY`. A possible solution would be to have a type guard like so
```ts
if(pricing.type === 'VariableAmountPricingResponse') {
    return 
} else {
   console.log(pricing.amount)
}
```
This would narrow the type since only the legacy type would be left in the else block, but this feels a bit flaky and less readable.

**Comment by tomas-zijdemans** [comment] 2024-11-05 08:06
Correct, you can narrow either way - probably nice to do that in a function as well.

Type guard is definitely a good solution here - I'll close the issue unless you see the need for a fix?

**Comment by spiftire** [comment] 2024-11-05 12:13
I really think this is an issue if the types does not represent the actual response from the API. It will probably cause issues for others trying to use the SDK.

**Comment by tomas-zijdemans** [comment] 2024-11-11 20:26
I'll close this issue soon, as it's working as intended. The union type pricingResponse represents the two different pricing responses that can be returned, and needs to be narrowed. When making the API call, both Legacy and Variable price response can be returned, so a union type is appropriate.
If you have thoughts on how to better type the response, please raise a PR to discuss a potential improvement

**Closed** 2024-11-12 08:28 UTC
